debug_scan:
  description:  Run raw scan for Bosch. It will be available as bosch_scan.json in your www dir of Home Assistant. You can check url of the file in logs after it. It doesn't matter which entity you choose. It makes scan for whole your setup. Typically it is https://ha/local/bosch_scan.json?vX
  fields:
    entity_id:
      description: Name(s) of entity. Choose one from Bosch component.
      example: 'climate.hc1'
update_thermostat:
  description:  Update thermostat data manually. Automatically it occurs every 30 seconds. Avoid to use it a lot as Bosch gateway might block requests for some time.
  fields:
    entity_id:
      description: Name(s) of entity. Choose one from Bosch component.
      example: 'climate.hc1'
    