debug_scan:
  description:  Run raw scan for Bosch. It will be available as bosch_scan.json in your www dir of Home Assistant. You can check url of the file in logs after it.
  fields:
    entity_id:
      description: Name(s) of entities to create snapshots from.
      example: 'camera.living_room_camera'